### ISSUE TITLE
refactoring notes

### ISSUE THREAD

**Issue by fs-tom** [fsdonks/run-amc#1]
@fs-craig 

For posterity:

We don't need to monkey patch rand-proj.  We can accomplish the rc record transforms at the project level and then pass that down stream with rand-proj being ignorant of the changes.

The legacy processing model / monkey patching assumed processing after the project was split by src, e.g. after rand-runs invoked.
We can easily do this at the aggregate project level.  Compute a map of {src quantity} derived from supply records and demand records grouped by src.  Then map over the demand records where src and category and compo match, updating quantity.  This promotes a general reuse or slight mod of most the auxillary functions.   Let's call this update-unfilled-demands.

Then we have a higher service-level function that takes a project and identical arguments for rand-runs (or whatever the current usage entry point is).  Inside here, the project is transformed by applying upate-unfilled-demands prior to sending it downstream (eventually to rand-proj).  No patching needed.  Everything lives in a run-amc namespace and delegates to existing functions in an additive manner.

**Comment by fs-craig** [comment]
@fs-tom

As it stands, we need to wait until we have chosen a specific RC inventory before modifying the cannibalization demand record.

Currently, we
split the project by src
create multiple projects for the inventories between the lower and upper inventory levels
then given one of those projects, we modify the rc cannibalization demand quantity depending on what the RC inventory is for this project that we're currently in.

We can still use a higher service-level function like you mention to assoc a flag onto the project such as :running-rc? true.

Then in rand-proj, we check for the existence of that flag in the project.  If that flag exists and is true, we call rc-proj on the project as is, throwing the exception if there is no :rc-unavailable for the supply record.  If the flag is false or doesn't exist, we keep the project as is.

**Comment by fs-craig** [comment]
@fs-tom 

We could keep track of transformations that we want to perform after the project is split by src for one inventory level by associng transformations onto the project like
(assoc proj :after-split-transforms [rc-proj [] random-initials [number-generator]])
where rc-proj takes no additional args beyond the project and random-initials would do the supply record randomization taking the project as an argument and one additional argument which is the random number-generator.

We'll want to add these transforms at different spots so I can write a add-transform(proj, fn-symbol, args) function that will add a new transform to that :after-split-transforms vector.

This will be similar to what I did in marathon.ces.entityfactory for the supply record preprocessing, so I might be able to reuse something from there, but this time, we want to apply these transforms to the whole proj and not just one record.

**Comment by fs-craig** [comment]
Pull request for this is pending in m4/master
